/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [{ type: "autogenerated", dirName: "tech" }],
  design: [{ type: "autogenerated", dirName: "design" }],
};

module.exports = sidebars;
